title: StaticTale
description: A clean file sharing platform for digital assets
baseurl: "/statictale"
url: "https://lazypwny751.github.io"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

collections:
  resources:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "resource"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
